-- Revert myBank:02.seeding from pg

BEGIN;

TRUNCATE TABLE "app_user" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "account" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "counterparty" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "category" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "operation_type" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "loan" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "transaction" RESTART IDENTITY CASCADE;

COMMIT;
